name: 'publish-action'
on: # rebuild any PRs and main branch changes
  release:
    types: [created]

jobs:
  package-and-publish: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: Checking out!
        uses: actions/checkout@v3
       
#       - name: Use Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '12.x'

#       - run: npm install
#       - run: npm run build --if-present

#       Job for Minify-JS
#       - name: Minify-JS Action
#         uses: jossydevers/minify-js@v1.0.0
#         with:
#           directory: 'src/component.js' # (OPTIONAL)
#           output: 'minify/src/' # (OPTIONAL)
        
      - name: Publish action 
        uses: actions-on-packages/package-action@0.4.1
#        with: 
#            path: 'dist/'
        
